# Google Cloud Run configuration
runtime: python313

# Basic scaling configuration
instance_class: F2
automatic_scaling:
  min_instances: 0
  max_instances: 5
  target_cpu_utilization: 0.75

# Environment variables (override in Cloud Console for sensitive data)
env_variables:
  STREAMLIT_SERVER_PORT: '8080'
  STREAMLIT_SERVER_ADDRESS: '0.0.0.0'
  STREAMLIT_SERVER_HEADLESS: 'true'

# Entry point
entrypoint: streamlit run app.py --server.port=8080 --server.address=0.0.0.0
